// This file is generated by the agent-sandbox CLI when building the channel manager.
// It registers all channel plugins discovered from the project's feature plugins.
// For the telegram example, we hardcode the telegram channel.
import type { Channel, ChannelFactory } from "./types.js";
import type { AcpAgent } from "../acp-client.js";
import createTelegramChannel from "./channel.js";

export const channels: Record<string, ChannelFactory> = {
  telegram: createTelegramChannel,
};

export function loadChannel(
  name: string,
  config: Record<string, unknown>,
  agent: AcpAgent
): Channel {
  const factory = channels[name];
  if (!factory) {
    throw new Error(`Unknown channel: ${name}. Available: ${Object.keys(channels).join(", ") || "none"}`);
  }
  return factory(config, agent);
}
