// This file is generated by the agent-sandbox CLI when building the bridge.
// It registers all channel plugins discovered from the project's feature plugins.
// In development, this stub is used so the bridge core compiles without plugins.
import type { Channel } from "./types.js";

export const channels: Record<string, new (config: unknown) => Channel> = {};
