FROM {{ .BaseImage }}

RUN useradd -m -s /bin/bash {{ .User }}

{{ range .Install -}}
RUN {{ . }}
{{ end -}}
{{ if .Install }}
{{ end -}}
{{ range .FeatureCmds -}}
RUN {{ . }}
{{ end -}}
{{ if .FeatureCmds }}
{{ end -}}
{{ if .HasHomeOverride -}}
COPY home-override/ /opt/home-override/

{{ end -}}
{{ if .HasHooks -}}
COPY hooks/ /opt/hooks/
RUN chmod +x /opt/hooks/*

{{ end -}}
{{ if .HasEntrypoint -}}
COPY entrypoint.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh

{{ end -}}
USER {{ .User }}
WORKDIR /home/{{ .User }}

{{ if .HasEntrypoint -}}
ENTRYPOINT ["/opt/entrypoint.sh"]
{{ else if .Cmd -}}
CMD [{{ range $i, $c := .Cmd }}{{ if $i }}, {{ end }}{{ quote $c }}{{ end }}]
{{ end -}}
