// This file is generated by the agent-sandbox CLI when building the channel manager.
// It registers all command plugins discovered from the project's feature plugins.
// In development, this stub is used so the channel manager compiles without plugins.
import type { CommandPlugin } from "./types.js";

export const commandPlugins: CommandPlugin[] = [];
