package generate

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"strings"

	sandbox "github.com/donbader/agent-sandbox"
)

// writeChannelManagerSource writes the embedded channel-manager source to .build/channel-manager-src/,
// copies plugin channel implementations, and generates the channel registry.
func (g *Generator) writeChannelManagerSource() error {
	destDir := filepath.Join(g.OutDir, "channel-manager-src")

	// 1. Copy channel-manager core source
	err := fs.WalkDir(sandbox.ChannelManagerSource, "channel-manager", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		relPath, err := filepath.Rel("channel-manager", path)
		if err != nil {
			return err
		}
		destPath := filepath.Join(destDir, relPath)

		if d.IsDir() {
			return os.MkdirAll(destPath, 0755)
		}

		data, err := sandbox.ChannelManagerSource.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(destPath, data, 0644)
	})
	if err != nil {
		return err
	}

	// 2. Copy plugin channel implementations and build registry
	channelDir := filepath.Join(destDir, "src", "channel")
	if err := os.MkdirAll(channelDir, 0755); err != nil {
		return err
	}

	var channels []string
	for _, f := range g.Features {
		if f.ChannelName == "" {
			continue
		}
		name := f.ChannelName
		channelRoot := fmt.Sprintf("internal/plugins/%s/channel", name)

		// Copy all .ts files from plugin's channel/ directory to channel-manager-src/src/channel/
		// channel.ts → src/channel/<name>.ts (special case)
		// other files placed as siblings: delivery/foo.ts → src/channel/delivery/foo.ts
		// Note: if multiple plugins contribute same-named files, last one wins.
		err := fs.WalkDir(sandbox.CorePlugins, channelRoot, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".ts") {
				return nil
			}
			// Skip test files
			if strings.HasSuffix(path, ".test.ts") {
				return nil
			}

			data, err := sandbox.CorePlugins.ReadFile(path)
			if err != nil {
				return err
			}

			// Determine destination path
			relPath, relErr := filepath.Rel(channelRoot, path)
			if relErr != nil {
				return fmt.Errorf("computing relative path for %s: %w", path, relErr)
			}
			var destPath string
			if relPath == "channel.ts" {
				// channel.ts → src/channel/<name>.ts
				destPath = filepath.Join(channelDir, name+".ts")
			} else {
				// other files → src/channel/<relPath> (sibling of channel file)
				destPath = filepath.Join(channelDir, relPath)
			}

			if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
				return err
			}
			return os.WriteFile(destPath, data, 0644)
		})
		if err != nil {
			return fmt.Errorf("plugin %q: copying channel files: %w", name, err)
		}
		channels = append(channels, name)
	}

	// 3. Generate channels.gen.ts registry
	return g.writeChannelRegistry(channelDir, channels)
}

// writeChannelRegistry generates src/channel/channels.gen.ts with imports for all plugin channels.
func (g *Generator) writeChannelRegistry(channelDir string, channels []string) error {
	var b strings.Builder
	b.WriteString("// Auto-generated by agent-sandbox generate. Do not edit.\n")
	b.WriteString("import type { Channel, ChannelFactory } from \"./types.js\";\n")
	b.WriteString("import type { AcpAgent } from \"../acp-client.js\";\n\n")

	for _, name := range channels {
		camelName := "create" + strings.ToUpper(name[:1]) + name[1:] + "Channel"
		_, _ = fmt.Fprintf(&b, "import %s from \"./%s.js\";\n", camelName, name)
	}

	b.WriteString("\nexport const channels: Record<string, ChannelFactory> = {\n")
	for _, name := range channels {
		camelName := "create" + strings.ToUpper(name[:1]) + name[1:] + "Channel"
		_, _ = fmt.Fprintf(&b, "  %s: %s,\n", name, camelName)
	}
	b.WriteString("};\n")

	b.WriteString("\nexport function loadChannel(\n")
	b.WriteString("  name: string,\n")
	b.WriteString("  config: Record<string, unknown>,\n")
	b.WriteString("  agent: AcpAgent\n")
	b.WriteString("): Channel {\n")
	b.WriteString("  const factory = channels[name];\n")
	b.WriteString("  if (!factory) {\n")
	b.WriteString("    throw new Error(`Unknown channel: ${name}. Available: ${Object.keys(channels).join(\", \") || \"none\"}`);\n")
	b.WriteString("  }\n")
	b.WriteString("  return factory(config, agent);\n")
	b.WriteString("}\n")

	path := filepath.Join(channelDir, "channels.gen.ts")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// writeCommandPlugins copies command plugin TypeScript source from feature plugins
// into channel-manager-src/src/command/ and generates a commands.gen.ts registry.
func (g *Generator) writeCommandPlugins() error {
	destDir := filepath.Join(g.OutDir, "channel-manager-src", "src", "command")

	// Collect features that contribute command plugins.
	var plugins []string
	for _, f := range g.Features {
		if f.CommandPluginDir == "" {
			continue
		}

		commandRoot := f.CommandPluginDir // already expanded to full embedded path by resolver

		// Extract plugin name from expanded path: "internal/plugins/<name>/command" → "<name>"
		parts := strings.Split(f.CommandPluginDir, "/")
		pluginName := parts[2] // internal/plugins/<name>/...

		err := fs.WalkDir(sandbox.CorePlugins, commandRoot, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(path, ".ts") {
				return nil
			}
			// Skip test files
			if strings.HasSuffix(path, ".test.ts") {
				return nil
			}

			data, err := sandbox.CorePlugins.ReadFile(path)
			if err != nil {
				return err
			}

			relPath, relErr := filepath.Rel(commandRoot, path)
			if relErr != nil {
				return fmt.Errorf("computing relative path for %s: %w", path, relErr)
			}

			// Copy into plugin subdirectory: src/command/<plugin-name>/<file>
			destPath := filepath.Join(destDir, pluginName, relPath)
			if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
				return err
			}
			return os.WriteFile(destPath, data, 0644)
		})
		if err != nil {
			return fmt.Errorf("plugin %q: copying command files: %w", pluginName, err)
		}
		plugins = append(plugins, pluginName)
	}

	if len(plugins) == 0 {
		return nil
	}

	// Ensure command directory exists for the registry.
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return err
	}

	// Generate commands.gen.ts registry.
	return g.writeCommandRegistry(destDir, plugins)
}

// writeCommandRegistry generates src/command/commands.gen.ts that imports and exports all command plugins.
func (g *Generator) writeCommandRegistry(commandDir string, plugins []string) error {
	var b strings.Builder
	b.WriteString("// Auto-generated by agent-sandbox generate. Do not edit.\n")
	b.WriteString("import type { CommandPlugin } from \"./types.js\";\n\n")

	for _, name := range plugins {
		// Convention: command plugin exports a default createPlugin function
		varName := strings.ReplaceAll(name, "-", "") + "Plugin"
		_, _ = fmt.Fprintf(&b, "import %s from \"./%s/%s.js\";\n", varName, name, name)
	}

	b.WriteString("\nexport const commandPlugins: CommandPlugin[] = [\n")
	for _, name := range plugins {
		varName := strings.ReplaceAll(name, "-", "") + "Plugin"
		_, _ = fmt.Fprintf(&b, "  %s,\n", varName)
	}
	b.WriteString("];\n")

	path := filepath.Join(commandDir, "commands.gen.ts")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// writeChannelConfig generates .build/channel-manager-config.json.
func (g *Generator) writeChannelConfig() error {
	channel := ""
	for _, f := range g.Features {
		if f.ChannelName != "" {
			channel = f.ChannelName
			break
		}
	}

	// ACP command runs directly (channel-manager already runs as agent user)
	config := map[string]any{
		"channel":     channel,
		"acp_command": g.Runtime.AcpCmd,
		"cwd":         g.Workdir,
	}

	// Pass plugin-specific config to channel-manager (generic — no plugin knowledge here)
	for _, f := range g.Features {
		maps.Copy(config, f.ChannelConfig)
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling channel-manager config: %w", err)
	}

	path := filepath.Join(g.OutDir, "channel-manager-config.json")
	return os.WriteFile(path, append(data, '\n'), 0644)
}
