# --- codex-switch:begin ---
model = "claude-opus-4.6"
model_provider = "agent_gateway_codex"
# --- codex-switch:end ---

model_catalog_json = "/home/agent/.codex/models.json"

[model_providers.agent_gateway_kiro]
name = "Agent Gateway (Kiro)"
base_url = "http://host.containers.internal:8000/v1"
http_headers = { Authorization = "Bearer dummy" }
wire_api = "responses"

[model_providers.agent_gateway_codex]
name = "Agent Gateway (Codex)"
base_url = "http://host.containers.internal:8000/v1"
http_headers = { Authorization = "Bearer dummy" }
wire_api = "responses"
